### ISSUE TITLE
CopperSpice Download page does not display in embedded HTML viewer

### ISSUE THREAD

**Issue by Zbyl** [copperspice/diamond#4]
A blank page is shown after going to Help > Diamond Help > Building > CopperSpice link > Download.
Same with Help > Diamond Help > Building > Diamond Source link.

Windows 10, Diamond Version: 1.2.3, Build # 05/01/2017

**Comment by bgeller** [comment]
The page you mentioned requires JavaScript and I had this turned off in the embedded WebKit Browser. 

I have changed Diamond to use your local Browser instead of the embedded WebKit browser. 

These changes were pushed to GitHub around June 9.  New binaries will be released in September before CppCon. 

Thanks for your report.
